### ISSUE TITLE
If you are using an angler, do the following.

### ISSUE THREAD

**Issue by cicada0014** [tosspayments/browser-sdk#2]
This repository uses regeneratorRuntime to use the latest JavaScript source.

Because Angular does not have this polyfill on its own, polyfills.ts file requires processing.

Otherwise.
`ReferenceError: regeneratorRuntime is not defined` error occuring.

So, `import 'regenerator-runtime/runtime';`  in polyfills.ts file at project root.
That'll solve the problem.

Angular 7 and below,
You may also need a core-js/stable polyfill.

Starting with the Angular 8 version, the CLI handles itself with core-js/stable, so you do not need to include this polyfill.

-----

이번에 토스페이먼츠 결제를 앵귤러 프로젝트에 연동하면서 regeneratorRuntime 관련 에러를 보게되었습니다. 
앵귤러 연동 과정에서 해당 폴리필이 없을 수 있으므로, 해당 안내를 해주시거나 모듈에 포함해주시기 바랍니다.

**Comment by HyunSeob** [comment]
어떤 방법이 좋을지 고민해본뒤 추가하겠습니다. 🙏 이슈 제보 감사합니다.

**Comment by HyunSeob** [comment]
@cicada0014 [v1.1.3 버전](https://www.npmjs.com/package/@tosspayments/sdk/v/1.1.3)에서 해결 됐을거라고 예상하는데, 혹시 문제점 다시 발생하면 알려주세요
