### ISSUE TITLE
typescript 5버전 지원 문의

### ISSUE THREAD

**Issue by badeagle85** [tosspayments/browser-sdk#92]
"@tosspayments/payment-widget-sdk": "^0.10.2", 사용중입니다.

지금 프로젝트에서 typescript를 5.3.3이용중인데요. 
아래와 같이 경고가 발생중인데 혹시 typescript 5버전 지원계획이 있으신가요?

```
npm WARN peerOptional overridden typescript@"^5.3.3" (was "^4.1.0") from @tosspayments/brandpay-types@0.2.6
npm WARN node_modules/@tosspayments/payment-widget__types/node_modules/@tosspayments/brandpay-types
npm WARN   @tosspayments/brandpay-types@"^0.2.6" from @tosspayments/payment-widget__types@1.0.1
npm WARN   node_modules/@tosspayments/payment-widget__types
```

**Comment by moresoo** [comment]
@badeagle85 안녕하세요.
[v0.11.1](https://www.npmjs.com/package/@tosspayments/payment-widget-sdk/v/0.11.1?activeTab=versions) 버전에서 typescript 5버전을 지원하도록 변경되었습니다!
